name: Deploy Markdown to Pages

on:
  push:
    branches: ["main"] # Triggers when you push to the main branch
  workflow_dispatch:     # Allows you to run the workflow manually

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
	runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: wranders/markdown-to-pages-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        files: |-
          docs/API_README.md
    - uses: actions/upload-pages-artifact@v3
      with:
        path: dist

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
	runs-on: ubuntu-latest
    steps:
    - uses: actions/deploy-pages@v4
      id: deployment
